### ISSUE TITLE
Uploader - Project Name Taken

### ISSUE THREAD

**Issue by AechDub** [mixer/cdk#99]
If the project name already exists and you're not an owner, the uploader does not handle the error.  We need to make sure the uploader is properly displaying error messages.

**Comment by NightmareJoker2** [comment]
Wait, why is that even a thing? And why do you use the name from the `project.json` file?
Shouldn't this just be ignored and the control upload simply be tied to the interactive project version?
This just caused me a headache of two hours trying to figure out why deployment got stuck after after cloning @mixer/cdk-preact-starter, opening the folder it in the CDK (which doesn't detect the `node_modules` directory isn't present because the dependencies aren't installed, yet, when you do this, either, by the way) and running `npm i && npm i --dev` (after which I had to restart it, too, to make it work...)

**Comment by connor4312** [comment]
Hi, thanks for your feedback. A single control bundle can be linked to multiple interactive projects, so it needs a unique identifier; the name from the package.json works well. Sorry for the headache, that should be resolved in our next release when the linked commit comes out.

>which doesn't detect the node_modules directory isn't present because the dependencies aren't installed

See https://github.com/mixer/cdk/issues/102

**Comment by gostay** [comment]
I wrote up a separate issue related to this: #125 (as a separate issue since it's a feature request different from this Project Name Taken error messaging), but it's relevant to this conversation, I think.

**Comment by NightmareJoker2** [comment]
> A single control bundle can be linked to multiple interactive projects, so it needs a unique identifier

If that is the case, then why is there no separation from the interactive projects and the control bundles and a way to manage the control bundles and which interactive project uses which control bundle instead? Like, how would I even go about authoring a control bundle, publishing it, letting my users use it for their interactive projects, and update it independently?

> the name from the `package.json` works well

Er, no. No, it doesn't. When working in a team, and I would think working on your first party solutions would have made this obvious immediately, I couldn't have all of them have unfettered access to the production bundle, or use it for testing, **or** have them all change the project name and fuzz about constantly having to avoid checking it into version control. That's just crazy talk.
Please generate a bundle ID randomly, store it locally for reuse, and dispose of uploaded bundles that aren't linked to any interactive projects.
